#!/bin/sh
### BEGIN INIT INFO
# Provides:          ss-local
# Required-Start:    $network $local_fs $remote_fs $syslog
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start sslocal at boot time
### END INIT INFO


#### /usr/local/bin/ss-local -c /etc/shadowsocks.json &


DAEMON=/usr/local/bin/ss-local
DESC=ShadowSockLocalClient
NAME=ss-local
PIDFILE=/var/run/$NAME.pid

test -x $DAEMON || exit 0

case "$1" in
  start)
    echo -n "Starting $DESC: "

    $DAEMON -c /etc/shadowsocks.json \
	1> /var/log/$NAME.log \
	2> /var/log/$NAME.err.log &
    echo $! > $PIDFILE
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    kill `cat $PIDFILE`
    rm -f $PIDFILE
    echo "$NAME."
    ;;
  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0

